FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3005

COPY apps/blog/.next/standalone ./
COPY apps/blog/.next/static ./apps/blog/.next/static
COPY apps/blog/public ./apps/blog/public

EXPOSE 3005
CMD ["node", "apps/blog/server.js"]
