FROM nginx:alpine

RUN rm -f /etc/nginx/conf.d/default.conf

COPY deploy/nginx-blog.conf /etc/nginx/conf.d/blog.conf
COPY apps/admin/build/client/ /usr/share/nginx/html/admin/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
