services:
  blog:
    image: ghcr.io/ljt741212/blog-client:latest
    container_name: blog-client
    restart: always
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      PORT: 3005
      API_URL: ${API_URL:-http://blog-server:3004/api}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-/api}
    networks:
      - blog_network

networks:
  blog_network:
    external: true
